const reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

function initCursorGlow(){if(reduceMotion)return;const glow=document.querySelector('.cursor-glow');window.addEventListener('mousemove',e=>{glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px';});}
function initMobileNav(){const btn=document.querySelector('.hamburger');const links=document.getElementById('nav-links');btn?.addEventListener('click',()=>{const open=links.classList.toggle('open');btn.setAttribute('aria-expanded',String(open));});}
function initSmoothScroll(){document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const id=a.getAttribute('href');if(id.length>1){const el=document.querySelector(id);if(el){e.preventDefault();el.scrollIntoView({behavior: reduceMotion ? 'auto':'smooth'});}}}));}
function initScrollAnimations(){const io=new IntersectionObserver(entries=>entries.forEach(en=>{if(en.isIntersecting)en.target.classList.add('visible');}),{threshold:.15});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
  const secs=[...document.querySelectorAll('main section[id]')],nav=[...document.querySelectorAll('.nav-links a[href^="#"]')];
  window.addEventListener('scroll',()=>{let current='';secs.forEach(s=>{if(window.scrollY>=s.offsetTop-120)current=s.id;});nav.forEach(n=>n.classList.toggle('active',n.getAttribute('href')==='#'+current));});}
function initStatsCounters(){const stats=document.querySelectorAll('[data-count]');const io=new IntersectionObserver(entries=>{entries.forEach(e=>{if(!e.isIntersecting)return;const el=e.target;const val=parseFloat(el.dataset.count);const suffix=el.dataset.suffix||'';const isFloat=String(val).includes('.');let i=0;const t=setInterval(()=>{i+=val/40; if(i>=val){i=val;clearInterval(t);} const n=isFloat?i.toFixed(1):Math.round(i);el.textContent=n+suffix;},20);io.unobserve(el);});},{threshold:.5});stats.forEach(s=>io.observe(s));}
function initGsapStats(){if(reduceMotion||window.innerWidth<801||!window.gsap||!window.ScrollTrigger)return;gsap.registerPlugin(ScrollTrigger);const pages=gsap.utils.toArray('.stat-page');pages.forEach((p,i)=>{if(i!==0)gsap.set(p,{autoAlpha:0,y:40,scale:.96});});
  const tl=gsap.timeline({scrollTrigger:{trigger:'.stats-scroll',start:'top top',end:`+=${pages.length*100}%`,scrub:1,pin:true,anticipatePin:1}});
  pages.forEach((page,i)=>{if(i===0)return;tl.to(pages[i-1],{autoAlpha:0,y:-60,scale:1.02,duration:.45},i-0.1).to(page,{autoAlpha:1,y:0,scale:1,duration:.45},i-0.1);});
  gsap.utils.toArray('.stat-3d').forEach(model=>{gsap.to(model,{rotate:360,duration:10,ease:'none',repeat:-1});gsap.to(model,{y:-16,duration:2.4,yoyo:true,repeat:-1,ease:'sine.inOut'});});
}
function hashString(str){let h=0;for(let i=0;i<str.length;i++)h=((h<<5)-h)+str.charCodeAt(i)|0;return Math.abs(h);}
function generateAuditResult(url){const h=hashString(url.toLowerCase());const score=42+(h%45);const load=((h%26)/10+1.8).toFixed(1);const target=Math.max(0.9,(load-(h%11)/10)).toFixed(1);const improve=Math.max(12,Math.min(58,Math.round((1-target/load)*100)));const metrics={mobile:52+h%44,seo:48+h%47,conversion:44+h%49,trust:50+h%43};
  const grade=score>=80?'A':score>=72?'B':score>=62?'C':score>=50?'D':'Needs rescue';
  const all=['Compress oversized images','Improve mobile spacing','Add clearer calls-to-action','Rewrite the hero section','Add trust signals and reviews','Improve page speed','Fix confusing navigation','Add local SEO structure','Make contact buttons easier to find','Add service-specific landing pages'];
  const suggestions=all.sort((a,b)=>(hashString(url+a)-hashString(url+b))).slice(0,score<60?6:4);
  return {url,score,grade,load,target,improve,metrics,suggestions};}
function renderAuditResult(r){const box=document.getElementById('audit-result');box.innerHTML=`<div class="glass card audit-card"><div><h3>${r.url} • ${r.score}/100 (${r.grade})</h3><p>We can improve your site loading speed by <strong>${r.improve}%</strong> — from ${r.load}s to ${r.target}s.</p><ul><li>Mobile readiness: ${r.metrics.mobile}% (confidence: medium)</li><li>SEO clarity: ${r.metrics.seo}% (confidence: medium)</li><li>Conversion strength: ${r.metrics.conversion}% (confidence: medium)</li><li>Trust score: ${r.metrics.trust}% (confidence: medium)</li></ul><h4>Action plan</h4><ul>${r.suggestions.map(s=>`<li>${s}</li>`).join('')}</ul><p><strong>Want us to fix this?</strong></p><p><a class="btn" href="#contact">Contact SitePilots</a> <a class="btn btn-ghost" href="#services">See what we'd change</a> <button id="download-audit" class="btn btn-ghost" type="button">Download mini audit</button></p></div><aside class="audit-preview" aria-label="Mini preview of submitted website"><div class="audit-preview-top"><span></span><span></span><span></span></div><iframe id="preview-frame" src="${r.url}" loading="lazy" referrerpolicy="no-referrer-when-downgrade" title="Website preview"></iframe><div id="preview-fallback" class="audit-preview-fallback">Preview blocked by site security headers.<br/>We can still run a full manual audit for you.</div></aside></div>`;
  const dl=document.getElementById('download-audit');dl?.addEventListener('click',()=>{const text=`SitePilots mini audit\nURL: ${r.url}\nScore: ${r.score}/100 (${r.grade})\nLoad: ${r.load}s -> ${r.target}s (${r.improve}% faster)\nActions:\n- ${r.suggestions.join('\n- ')}`;const blob=new Blob([text],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='sitepilots-mini-audit.txt';a.click();URL.revokeObjectURL(a.href);});
  const frame=document.getElementById('preview-frame');frame?.addEventListener('error',()=>{const fb=document.getElementById('preview-fallback');if(fb)fb.style.display='grid';frame.style.display='none';});
}
function initAuditTool(){const input=document.getElementById('website-url');const btn=document.getElementById('scan-btn');const status=document.getElementById('scan-status');const ui=document.getElementById('scan-ui');const progress=document.getElementById('scan-progress');const steps=['Checking first impression…','Testing mobile layout…','Estimating load speed…','Finding missed conversions…','Building your SitePilots action plan…'];
btn?.addEventListener('click',()=>{if(!input.value.trim()){status.textContent='Please paste a website URL first.';ui.hidden=false;return;}let url=input.value.trim();if(!/^https?:\/\//i.test(url))url='https://'+url;input.value=url;ui.hidden=false;progress.style.width='0%';let i=0;const tick=()=>{status.textContent=steps[i];progress.style.width=((i+1)/steps.length*100)+'%';i++;if(i<steps.length){setTimeout(tick,450);}else{setTimeout(()=>renderAuditResult(generateAuditResult(url)),300);}};tick();});}
function initContactForm(){const f=document.getElementById('contact-form');const msg=document.getElementById('form-success');f?.addEventListener('submit',e=>{e.preventDefault();if(!f.reportValidity())return;const data=new FormData(f);const body=[`Name: ${data.get('name')}`,`Business: ${data.get('business')}`,`Business type: ${data.get('type')}`,`Website: ${data.get('website')}`,`Timeline: ${data.get('timeline')}`,`Traffic: ${data.get('traffic')}`,`Platform: ${data.get('platform')}`,`Help needed: ${data.get('help')}`,`Budget: ${data.get('budget')}`].join('\n');window.location.href=`mailto:hello@sitepilots.co.uk?subject=${encodeURIComponent('New SitePilots website enquiry')}&body=${encodeURIComponent(body)}`;msg.textContent='Your email app should open now. Send the message and we’ll take it from there.';});}
function initEstimator(){const pages=document.getElementById('est-pages'),seo=document.getElementById('est-seo'),copy=document.getElementById('est-copy'),booking=document.getElementById('est-booking'),out=document.getElementById('estimate-value');if(!pages||!seo||!copy||!booking||!out)return;const calc=()=>{const min=220+Number(pages.value)*95+Number(seo.value)*140+Number(copy.value)*180+Number(booking.value)*160;const max=Math.round(min*1.55);out.textContent=`£${min} - £${max}`;};[pages,seo,copy,booking].forEach(el=>el.addEventListener('input',calc));calc();}
function initBackToTop(){const b=document.getElementById('back-to-top');window.addEventListener('scroll',()=>b.style.display=window.scrollY>500?'block':'none');b?.addEventListener('click',()=>window.scrollTo({top:0,behavior:reduceMotion?'auto':'smooth'}));}

function initTiltCards(){if(window.innerWidth<900||reduceMotion)return;document.querySelectorAll('.tilt').forEach(card=>{card.addEventListener('mousemove',e=>{const r=card.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;card.style.transform=`rotateX(${(-y*8).toFixed(2)}deg) rotateY(${(x*10).toFixed(2)}deg)`;});card.addEventListener('mouseleave',()=>card.style.transform='');});}

initCursorGlow();initMobileNav();initSmoothScroll();initScrollAnimations();initStatsCounters();initGsapStats();initAuditTool();initContactForm();initEstimator();initBackToTop();initTiltCards();
