const reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

function initCursorGlow(){if(reduceMotion)return;const g=document.querySelector('.cursor-glow');window.addEventListener('mousemove',e=>{g.style.left=e.clientX+'px';g.style.top=e.clientY+'px';});}
function initMobileNav(){const b=document.querySelector('.hamburger');const n=document.getElementById('nav-links');b?.addEventListener('click',()=>{const o=n.classList.toggle('open');b.setAttribute('aria-expanded',String(o));});}
function initSmoothScroll(){document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const id=a.getAttribute('href');const el=id&&document.querySelector(id);if(el){e.preventDefault();el.scrollIntoView({behavior:reduceMotion?'auto':'smooth'});}}));}
function initScrollAnimations(){const io=new IntersectionObserver(es=>es.forEach(x=>x.isIntersecting&&x.target.classList.add('visible')),{threshold:.2});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));const secs=[...document.querySelectorAll('main section[id]')],links=[...document.querySelectorAll('.nav-links a[href^="#"]')];window.addEventListener('scroll',()=>{let cur='';secs.forEach(s=>{if(scrollY>=s.offsetTop-140)cur=s.id;});links.forEach(l=>l.classList.toggle('active',l.getAttribute('href')==='#'+cur));});}
function initStatsCounters(){const nodes=document.querySelectorAll('.gradient-stat');const io=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;const n=e.target,v=parseFloat(n.dataset.count),s=n.dataset.suffix||'';let i=0;const f=String(v).includes('.');const t=setInterval(()=>{i+=v/35;if(i>=v){i=v;clearInterval(t);}n.textContent=(f?i.toFixed(1):Math.round(i))+s;},25);io.unobserve(n);}),{threshold:.5});nodes.forEach(n=>io.observe(n));}
function hashString(str){let h=0;for(let i=0;i<str.length;i++)h=(h<<5)-h+str.charCodeAt(i)|0;return Math.abs(h);}
function generateAuditResult(url){const h=hashString(url.toLowerCase());const score=42+(h%45),load=Number(((h%26)/10+1.8).toFixed(1));const factor=.42+(h%19)/100;const target=Number(Math.max(1,(load*factor)).toFixed(1));const improve=Math.max(20,Math.min(64,Math.round((1-target/load)*100)));const m={mobile:52+h%44,seo:48+h%47,conversion:44+h%49,trust:50+h%43};const grade=score>=80?'A':score>=72?'B':score>=62?'C':score>=50?'D':'Needs rescue';const s=['Compress oversized images','Improve mobile spacing','Add clearer calls-to-action','Rewrite hero message for outcomes','Add trust signals and reviews','Improve page speed','Fix confusing navigation','Add local SEO structure','Make contact buttons easier to find','Add service-specific landing pages'];const suggestions=s.sort((a,b)=>hashString(url+a)-hashString(url+b)).slice(0,score<60?6:4);return{url,score,grade,load,target,improve,m,suggestions};}
function renderAuditResult(r){document.getElementById('audit-result').innerHTML=`<div class="glass card audit-result-wrap"><div><h3>${r.url} · ${r.score}/100 (${r.grade})</h3><p>We can improve your site loading speed by ${r.improve}% — from ${r.load}s to ${r.target}s.</p><ul><li>Mobile readiness: ${r.m.mobile}%</li><li>SEO clarity: ${r.m.seo}%</li><li>Conversion strength: ${r.m.conversion}%</li><li>Trust score: ${r.m.trust}%</li></ul><h4>Priority changes</h4><ul>${r.suggestions.map(x=>`<li>${x}</li>`).join('')}</ul><p><strong>Want us to fix this?</strong></p><p><a class="btn" href="#contact">Contact SitePilots</a> <a class="btn btn-ghost" href="#services">See what we'd change</a></p></div><aside class="mini-preview" aria-label="Preview mockup"><div class="mini-top"></div><div class="mini-hero"></div><div class="mini-line" style="width:95%"></div><div class="mini-line" style="width:88%"></div><div class="mini-line" style="width:75%"></div><div class="mini-cta"></div></aside></div>`;}
function initAuditTool(){const i=document.getElementById('website-url'),b=document.getElementById('scan-btn'),u=document.getElementById('scan-ui'),p=document.getElementById('scan-progress'),s=document.getElementById('scan-status');const steps=['Checking first impression…','Testing mobile layout…','Estimating load speed…','Finding missed conversions…','Building your SitePilots action plan…'];b?.addEventListener('click',()=>{if(!i.value.trim()){u.hidden=false;s.textContent='Please paste a website URL first.';return;}let url=i.value.trim();if(!/^https?:\/\//i.test(url))url='https://'+url;i.value=url;u.hidden=false;p.style.width='0%';let x=0;const run=()=>{s.textContent=steps[x];p.style.width=((x+1)/steps.length*100)+'%';x++;if(x<steps.length){setTimeout(run,500);}else{setTimeout(()=>renderAuditResult(generateAuditResult(url)),350);}};run();});}
function initContactForm(){const f=document.getElementById('contact-form'),m=document.getElementById('form-success');f?.addEventListener('submit',e=>{e.preventDefault();if(!f.reportValidity())return;const d=new FormData(f);const body=[`Name: ${d.get('name')}`,`Business: ${d.get('business')}`,`Website: ${d.get('website')}`,`Help: ${d.get('help')}`,`Budget: ${d.get('budget')}`].join('\n');location.href=`mailto:hello@sitepilots.co.uk?subject=${encodeURIComponent('New SitePilots website enquiry')}&body=${encodeURIComponent(body)}`;m.textContent='Your email app should open now. Send the message and we’ll take it from there.';});}
function initBackToTop(){const b=document.getElementById('back-to-top');addEventListener('scroll',()=>b.style.display=scrollY>500?'block':'none');b?.addEventListener('click',()=>scrollTo({top:0,behavior:reduceMotion?'auto':'smooth'}));}
function initTiltCards(){if(reduceMotion||innerWidth<900)return;document.querySelectorAll('.tilt').forEach(c=>{c.addEventListener('mousemove',e=>{const r=c.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;c.style.transform=`rotateX(${(-y*8).toFixed(2)}deg) rotateY(${(x*10).toFixed(2)}deg) translateY(-8px)`;});c.addEventListener('mouseleave',()=>c.style.transform='');});}

initCursorGlow();initMobileNav();initSmoothScroll();initScrollAnimations();initStatsCounters();initAuditTool();initContactForm();initBackToTop();initTiltCards();
